// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: plugin.v1.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigureBackend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigureBackend) Reset() {
	*x = ConfigureBackend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureBackend) ProtoMessage() {}

func (x *ConfigureBackend) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureBackend.ProtoReflect.Descriptor instead.
func (*ConfigureBackend) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{0}
}

type CreateWorkspace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateWorkspace) Reset() {
	*x = CreateWorkspace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspace) ProtoMessage() {}

func (x *CreateWorkspace) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspace.ProtoReflect.Descriptor instead.
func (*CreateWorkspace) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{1}
}

type DeleteWorkspace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteWorkspace) Reset() {
	*x = DeleteWorkspace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWorkspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspace) ProtoMessage() {}

func (x *DeleteWorkspace) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspace.ProtoReflect.Descriptor instead.
func (*DeleteWorkspace) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{2}
}

type ListWorkspaces struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListWorkspaces) Reset() {
	*x = ListWorkspaces{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWorkspaces) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspaces) ProtoMessage() {}

func (x *ListWorkspaces) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspaces.ProtoReflect.Descriptor instead.
func (*ListWorkspaces) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{3}
}

type GetStatePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStatePayload) Reset() {
	*x = GetStatePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatePayload) ProtoMessage() {}

func (x *GetStatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatePayload.ProtoReflect.Descriptor instead.
func (*GetStatePayload) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{4}
}

type StatePayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Md5  []byte `protobuf:"bytes,1,opt,name=md5,proto3" json:"md5,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StatePayload) Reset() {
	*x = StatePayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatePayload) ProtoMessage() {}

func (x *StatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatePayload.ProtoReflect.Descriptor instead.
func (*StatePayload) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{5}
}

func (x *StatePayload) GetMd5() []byte {
	if x != nil {
		return x.Md5
	}
	return nil
}

func (x *StatePayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PutState) Reset() {
	*x = PutState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutState) ProtoMessage() {}

func (x *PutState) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutState.ProtoReflect.Descriptor instead.
func (*PutState) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{6}
}

type DeleteState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteState) Reset() {
	*x = DeleteState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteState) ProtoMessage() {}

func (x *DeleteState) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteState.ProtoReflect.Descriptor instead.
func (*DeleteState) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{7}
}

type StateLock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StateLock) Reset() {
	*x = StateLock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateLock) ProtoMessage() {}

func (x *StateLock) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateLock.ProtoReflect.Descriptor instead.
func (*StateLock) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{8}
}

type StateUnlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StateUnlock) Reset() {
	*x = StateUnlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateUnlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUnlock) ProtoMessage() {}

func (x *StateUnlock) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUnlock.ProtoReflect.Descriptor instead.
func (*StateUnlock) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{9}
}

type StateLockInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Operation string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Info      string                 `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Who       string                 `protobuf:"bytes,4,opt,name=who,proto3" json:"who,omitempty"`
	Version   string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Created   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	Path      string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *StateLockInfo) Reset() {
	*x = StateLockInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateLockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateLockInfo) ProtoMessage() {}

func (x *StateLockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateLockInfo.ProtoReflect.Descriptor instead.
func (*StateLockInfo) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{10}
}

func (x *StateLockInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StateLockInfo) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *StateLockInfo) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *StateLockInfo) GetWho() string {
	if x != nil {
		return x.Who
	}
	return ""
}

func (x *StateLockInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StateLockInfo) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *StateLockInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ConfigureBackend_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config map[string]string `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ConfigureBackend_Request) Reset() {
	*x = ConfigureBackend_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureBackend_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureBackend_Request) ProtoMessage() {}

func (x *ConfigureBackend_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureBackend_Request.ProtoReflect.Descriptor instead.
func (*ConfigureBackend_Request) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ConfigureBackend_Request) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConfigureBackend_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []string `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *ConfigureBackend_Response) Reset() {
	*x = ConfigureBackend_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureBackend_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureBackend_Response) ProtoMessage() {}

func (x *ConfigureBackend_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureBackend_Response.ProtoReflect.Descriptor instead.
func (*ConfigureBackend_Response) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ConfigureBackend_Response) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type CreateWorkspace_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workspace string `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
}

func (x *CreateWorkspace_Request) Reset() {
	*x = CreateWorkspace_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkspace_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspace_Request) ProtoMessage() {}

func (x *CreateWorkspace_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspace_Request.ProtoReflect.Descriptor instead.
func (*CreateWorkspace_Request) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CreateWorkspace_Request) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type CreateWorkspace_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []string `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *CreateWorkspace_Response) Reset() {
	*x = CreateWorkspace_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkspace_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspace_Response) ProtoMessage() {}

func (x *CreateWorkspace_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspace_Response.ProtoReflect.Descriptor instead.
func (*CreateWorkspace_Response) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{1, 1}
}

func (x *CreateWorkspace_Response) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type DeleteWorkspace_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workspace string `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Force     bool   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
}

func (x *DeleteWorkspace_Request) Reset() {
	*x = DeleteWorkspace_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWorkspace_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspace_Request) ProtoMessage() {}

func (x *DeleteWorkspace_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspace_Request.ProtoReflect.Descriptor instead.
func (*DeleteWorkspace_Request) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{2, 0}
}

func (x *DeleteWorkspace_Request) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *DeleteWorkspace_Request) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DeleteWorkspace_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []string `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *DeleteWorkspace_Response) Reset() {
	*x = DeleteWorkspace_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWorkspace_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspace_Response) ProtoMessage() {}

func (x *DeleteWorkspace_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspace_Response.ProtoReflect.Descriptor instead.
func (*DeleteWorkspace_Response) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{2, 1}
}

func (x *DeleteWorkspace_Response) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ListWorkspaces_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListWorkspaces_Request) Reset() {
	*x = ListWorkspaces_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWorkspaces_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspaces_Request) ProtoMessage() {}

func (x *ListWorkspaces_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspaces_Request.ProtoReflect.Descriptor instead.
func (*ListWorkspaces_Request) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{3, 0}
}

type ListWorkspaces_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workspaces []string `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	Errors     []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *ListWorkspaces_Response) Reset() {
	*x = ListWorkspaces_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWorkspaces_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspaces_Response) ProtoMessage() {}

func (x *ListWorkspaces_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspaces_Response.ProtoReflect.Descriptor instead.
func (*ListWorkspaces_Response) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ListWorkspaces_Response) GetWorkspaces() []string {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

func (x *ListWorkspaces_Response) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type GetStatePayload_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workspace string `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
}

func (x *GetStatePayload_Request) Reset() {
	*x = GetStatePayload_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatePayload_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatePayload_Request) ProtoMessage() {}

func (x *GetStatePayload_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatePayload_Request.ProtoReflect.Descriptor instead.
func (*GetStatePayload_Request) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetStatePayload_Request) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type GetStatePayload_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload *StatePayload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Errors  []string      `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *GetStatePayload_Response) Reset() {
	*x = GetStatePayload_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatePayload_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatePayload_Response) ProtoMessage() {}

func (x *GetStatePayload_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatePayload_Response.ProtoReflect.Descriptor instead.
func (*GetStatePayload_Response) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{4, 1}
}

func (x *GetStatePayload_Response) GetPayload() *StatePayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GetStatePayload_Response) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type PutState_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workspace string `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Data      []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PutState_Request) Reset() {
	*x = PutState_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutState_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutState_Request) ProtoMessage() {}

func (x *PutState_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutState_Request.ProtoReflect.Descriptor instead.
func (*PutState_Request) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{6, 0}
}

func (x *PutState_Request) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *PutState_Request) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutState_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []string `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *PutState_Response) Reset() {
	*x = PutState_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutState_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutState_Response) ProtoMessage() {}

func (x *PutState_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutState_Response.ProtoReflect.Descriptor instead.
func (*PutState_Response) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{6, 1}
}

func (x *PutState_Response) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type DeleteState_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workspace string `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
}

func (x *DeleteState_Request) Reset() {
	*x = DeleteState_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteState_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteState_Request) ProtoMessage() {}

func (x *DeleteState_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteState_Request.ProtoReflect.Descriptor instead.
func (*DeleteState_Request) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{7, 0}
}

func (x *DeleteState_Request) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type DeleteState_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []string `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *DeleteState_Response) Reset() {
	*x = DeleteState_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteState_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteState_Response) ProtoMessage() {}

func (x *DeleteState_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteState_Response.ProtoReflect.Descriptor instead.
func (*DeleteState_Response) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{7, 1}
}

func (x *DeleteState_Response) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type StateLock_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workspace string         `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Info      *StateLockInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *StateLock_Request) Reset() {
	*x = StateLock_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateLock_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateLock_Request) ProtoMessage() {}

func (x *StateLock_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateLock_Request.ProtoReflect.Descriptor instead.
func (*StateLock_Request) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{8, 0}
}

func (x *StateLock_Request) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *StateLock_Request) GetInfo() *StateLockInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type StateLock_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Errors []string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *StateLock_Response) Reset() {
	*x = StateLock_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateLock_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateLock_Response) ProtoMessage() {}

func (x *StateLock_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateLock_Response.ProtoReflect.Descriptor instead.
func (*StateLock_Response) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{8, 1}
}

func (x *StateLock_Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StateLock_Response) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type StateUnlock_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workspace string `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StateUnlock_Request) Reset() {
	*x = StateUnlock_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateUnlock_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUnlock_Request) ProtoMessage() {}

func (x *StateUnlock_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUnlock_Request.ProtoReflect.Descriptor instead.
func (*StateUnlock_Request) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{9, 0}
}

func (x *StateUnlock_Request) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *StateUnlock_Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StateUnlock_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errors []string `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *StateUnlock_Response) Reset() {
	*x = StateUnlock_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_v1_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateUnlock_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUnlock_Response) ProtoMessage() {}

func (x *StateUnlock_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUnlock_Response.ProtoReflect.Descriptor instead.
func (*StateUnlock_Response) Descriptor() ([]byte, []int) {
	return file_plugin_v1_proto_rawDescGZIP(), []int{9, 1}
}

func (x *StateUnlock_Response) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_plugin_v1_proto protoreflect.FileDescriptor

var file_plugin_v1_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xbc, 0x01, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65,
	0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x1a, 0x83, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x42,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x1a, 0x39, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x22, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x22, 0x5e, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x1a, 0x27, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x1a, 0x22, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x22, 0x74, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x1a, 0x3d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f,
	0x72, 0x63, 0x65, 0x1a, 0x22, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x5f, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x57,
	0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x42, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x87, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x27, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x1a, 0x4b, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x27, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x22, 0x34, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x6d, 0x64, 0x35, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6b, 0x0a, 0x08, 0x50, 0x75, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x1a, 0x3b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x1a, 0x22, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x5a, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x1a, 0x27, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x1a, 0x22, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x22, 0x8c, 0x01, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x1a,
	0x4b, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4c, 0x6f,
	0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x1a, 0x32, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x22, 0x6a, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x1a,
	0x37, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x1a, 0x22, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0xc7, 0x01, 0x0a,
	0x0d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x12, 0x10, 0x0a, 0x03, 0x77, 0x68, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x77,
	0x68, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x32, 0xd2, 0x04, 0x0a, 0x07, 0x42, 0x61, 0x63, 0x6b, 0x65,
	0x6e, 0x64, 0x12, 0x49, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x42,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12, 0x19, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x42, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a,
	0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x12, 0x18, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57,
	0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x18, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a,
	0x0e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x12,
	0x17, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57,
	0x6f, 0x72, 0x6b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x46, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x50, 0x75,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x50, 0x75, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x50, 0x75, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a,
	0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x4c, 0x6f, 0x63,
	0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4c, 0x6f,
	0x63, 0x6b, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3a, 0x0a, 0x0b, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x55, 0x6e, 0x6c, 0x6f,
	0x63, 0x6b, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plugin_v1_proto_rawDescOnce sync.Once
	file_plugin_v1_proto_rawDescData = file_plugin_v1_proto_rawDesc
)

func file_plugin_v1_proto_rawDescGZIP() []byte {
	file_plugin_v1_proto_rawDescOnce.Do(func() {
		file_plugin_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_plugin_v1_proto_rawDescData)
	})
	return file_plugin_v1_proto_rawDescData
}

var file_plugin_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_plugin_v1_proto_goTypes = []interface{}{
	(*ConfigureBackend)(nil),          // 0: ConfigureBackend
	(*CreateWorkspace)(nil),           // 1: CreateWorkspace
	(*DeleteWorkspace)(nil),           // 2: DeleteWorkspace
	(*ListWorkspaces)(nil),            // 3: ListWorkspaces
	(*GetStatePayload)(nil),           // 4: GetStatePayload
	(*StatePayload)(nil),              // 5: StatePayload
	(*PutState)(nil),                  // 6: PutState
	(*DeleteState)(nil),               // 7: DeleteState
	(*StateLock)(nil),                 // 8: StateLock
	(*StateUnlock)(nil),               // 9: StateUnlock
	(*StateLockInfo)(nil),             // 10: StateLockInfo
	(*ConfigureBackend_Request)(nil),  // 11: ConfigureBackend.Request
	(*ConfigureBackend_Response)(nil), // 12: ConfigureBackend.Response
	nil,                               // 13: ConfigureBackend.Request.ConfigEntry
	(*CreateWorkspace_Request)(nil),   // 14: CreateWorkspace.Request
	(*CreateWorkspace_Response)(nil),  // 15: CreateWorkspace.Response
	(*DeleteWorkspace_Request)(nil),   // 16: DeleteWorkspace.Request
	(*DeleteWorkspace_Response)(nil),  // 17: DeleteWorkspace.Response
	(*ListWorkspaces_Request)(nil),    // 18: ListWorkspaces.Request
	(*ListWorkspaces_Response)(nil),   // 19: ListWorkspaces.Response
	(*GetStatePayload_Request)(nil),   // 20: GetStatePayload.Request
	(*GetStatePayload_Response)(nil),  // 21: GetStatePayload.Response
	(*PutState_Request)(nil),          // 22: PutState.Request
	(*PutState_Response)(nil),         // 23: PutState.Response
	(*DeleteState_Request)(nil),       // 24: DeleteState.Request
	(*DeleteState_Response)(nil),      // 25: DeleteState.Response
	(*StateLock_Request)(nil),         // 26: StateLock.Request
	(*StateLock_Response)(nil),        // 27: StateLock.Response
	(*StateUnlock_Request)(nil),       // 28: StateUnlock.Request
	(*StateUnlock_Response)(nil),      // 29: StateUnlock.Response
	(*timestamppb.Timestamp)(nil),     // 30: google.protobuf.Timestamp
}
var file_plugin_v1_proto_depIdxs = []int32{
	30, // 0: StateLockInfo.created:type_name -> google.protobuf.Timestamp
	13, // 1: ConfigureBackend.Request.config:type_name -> ConfigureBackend.Request.ConfigEntry
	5,  // 2: GetStatePayload.Response.payload:type_name -> StatePayload
	10, // 3: StateLock.Request.info:type_name -> StateLockInfo
	11, // 4: Backend.ConfigureBackend:input_type -> ConfigureBackend.Request
	14, // 5: Backend.CreateWorkspace:input_type -> CreateWorkspace.Request
	16, // 6: Backend.DeleteWorkspace:input_type -> DeleteWorkspace.Request
	18, // 7: Backend.ListWorkspaces:input_type -> ListWorkspaces.Request
	20, // 8: Backend.GetStatePayload:input_type -> GetStatePayload.Request
	22, // 9: Backend.PutState:input_type -> PutState.Request
	24, // 10: Backend.DeleteState:input_type -> DeleteState.Request
	26, // 11: Backend.LockState:input_type -> StateLock.Request
	28, // 12: Backend.UnlockState:input_type -> StateUnlock.Request
	12, // 13: Backend.ConfigureBackend:output_type -> ConfigureBackend.Response
	15, // 14: Backend.CreateWorkspace:output_type -> CreateWorkspace.Response
	17, // 15: Backend.DeleteWorkspace:output_type -> DeleteWorkspace.Response
	19, // 16: Backend.ListWorkspaces:output_type -> ListWorkspaces.Response
	21, // 17: Backend.GetStatePayload:output_type -> GetStatePayload.Response
	23, // 18: Backend.PutState:output_type -> PutState.Response
	25, // 19: Backend.DeleteState:output_type -> DeleteState.Response
	27, // 20: Backend.LockState:output_type -> StateLock.Response
	29, // 21: Backend.UnlockState:output_type -> StateUnlock.Response
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_plugin_v1_proto_init() }
func file_plugin_v1_proto_init() {
	if File_plugin_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plugin_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigureBackend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorkspace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWorkspace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWorkspaces); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatePayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateLock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateUnlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateLockInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigureBackend_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigureBackend_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorkspace_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorkspace_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWorkspace_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWorkspace_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWorkspaces_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWorkspaces_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatePayload_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatePayload_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutState_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutState_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteState_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteState_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateLock_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateLock_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateUnlock_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_v1_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateUnlock_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plugin_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_proto_goTypes,
		DependencyIndexes: file_plugin_v1_proto_depIdxs,
		MessageInfos:      file_plugin_v1_proto_msgTypes,
	}.Build()
	File_plugin_v1_proto = out.File
	file_plugin_v1_proto_rawDesc = nil
	file_plugin_v1_proto_goTypes = nil
	file_plugin_v1_proto_depIdxs = nil
}
